version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test_adminname
      POSTGRES_PASSWORD: test_1234password
      POSTGRES_DB: test_lab4db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: test_adminname
      DB_PASSWORD: test_1234password
      DB_NAME: test_lab4db
      JWT_SECRET: test-lab4-secret-key
    depends_on:
      - db
